
export const ADD_CONTACT = "ADD_CONTACT"
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const GET_CONTACT = 'GET_CONTACT'
export const SELECT_CONTACT = 'SELECT_CONTACT'
export const CLEAR_CONTACT = "CLEAR_CONTACT"
export const DELETE_SELECTED_CONTACT = "DELETE_SELECTED_CONTACT"